---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bakery
subjects:
- kind: ServiceAccount
  name: bakery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bakery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bakery-agent
subjects:
- kind: ServiceAccount
  name: bakery-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bakery-agent