---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bakery
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/bakery-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bakery-agent
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/bakery-agent
