---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sa.yaml
- role.yaml
- rolebinding.yaml
- deploy.yaml
- svc.yaml
- ing.yaml
configMapGenerator:
- name: build
  files:
  - configs/config.yaml
secretGenerator:
- name: build
  envs:
  - .env
images:
- name: docker.io/rayshoo/bakery-server
  newTag: v1.0.0
