---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build
subjects:
- kind: ServiceAccount
  name: build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-agent
subjects:
- kind: ServiceAccount
  name: build-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-agent