---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/build-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-agent
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/build-agent
